// Generated by scripts/generate-database-types.mjs.
// Source: versioned SQL migrations in supabase/migrations.
// Do not edit this file manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      aggregate_snapshots: {
        Row: {
          id: string;
          season_id: string;
          category_id: string;
          prediction_intention: Database["public"]["Enums"]["prediction_intention"];
          kind: Database["public"]["Enums"]["aggregate_snapshot_kind"];
          cutoff_at: string;
          time_zone: string;
          method_version: string;
          schema_version: string;
          content_hash: string;
          payload: Json;
          active_source_ids: string[];
          locked_at: string;
          locked_by: string;
          corrects_snapshot_id: string | null;
          correction_reason: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          season_id: string;
          category_id: string;
          prediction_intention: Database["public"]["Enums"]["prediction_intention"];
          kind: Database["public"]["Enums"]["aggregate_snapshot_kind"];
          cutoff_at: string;
          time_zone: string;
          method_version: string;
          schema_version: string;
          content_hash: string;
          payload: Json;
          active_source_ids: string[];
          locked_at: string;
          locked_by: string;
          corrects_snapshot_id?: string | null;
          correction_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          season_id?: string;
          category_id?: string;
          prediction_intention?: Database["public"]["Enums"]["prediction_intention"];
          kind?: Database["public"]["Enums"]["aggregate_snapshot_kind"];
          cutoff_at?: string;
          time_zone?: string;
          method_version?: string;
          schema_version?: string;
          content_hash?: string;
          payload?: Json;
          active_source_ids?: string[];
          locked_at?: string;
          locked_by?: string;
          corrects_snapshot_id?: string | null;
          correction_reason?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "aggregate_snapshots_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "aggregate_snapshots_corrects_snapshot_id_fkey";
            columns: ["corrects_snapshot_id"];
            isOneToOne: false;
            referencedRelation: "aggregate_snapshots";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "aggregate_snapshots_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      categories: {
        Row: {
          id: string;
          name: string;
          subject: Database["public"]["Enums"]["category_subject"];
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          is_public: boolean;
          candidate_kind: string;
        };
        Insert: {
          id: string;
          name: string;
          subject: Database["public"]["Enums"]["category_subject"];
          display_order: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          is_public?: boolean;
          candidate_kind?: string;
        };
        Update: {
          id?: string;
          name?: string;
          subject?: Database["public"]["Enums"]["category_subject"];
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          is_public?: boolean;
          candidate_kind?: string;
        };
        Relationships: [];
      };
      category_candidate_match_history: {
        Row: {
          id: number;
          source_id: string;
          season_id: string;
          category_id: string;
          normalized_subject: string;
          category_candidate_id: string;
          match_kind: string;
          reason: string;
          actor: string;
          created_at: string;
        };
        Insert: {
          id: number;
          source_id: string;
          season_id: string;
          category_id: string;
          normalized_subject: string;
          category_candidate_id: string;
          match_kind: string;
          reason: string;
          actor: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          source_id?: string;
          season_id?: string;
          category_id?: string;
          normalized_subject?: string;
          category_candidate_id?: string;
          match_kind?: string;
          reason?: string;
          actor?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "category_candidate_match_history_category_candidate_id_fkey";
            columns: ["category_candidate_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_candidate_match_history_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_candidate_match_history_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_candidate_match_history_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      category_candidate_people: {
        Row: {
          category_candidate_id: string;
          person_id: string;
          role: string;
          display_order: number;
          created_at: string;
        };
        Insert: {
          category_candidate_id: string;
          person_id: string;
          role: string;
          display_order: number;
          created_at?: string;
        };
        Update: {
          category_candidate_id?: string;
          person_id?: string;
          role?: string;
          display_order?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "category_candidate_people_category_candidate_id_fkey";
            columns: ["category_candidate_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_candidate_people_person_id_fkey";
            columns: ["person_id"];
            isOneToOne: false;
            referencedRelation: "people";
            referencedColumns: ["id"];
          },
        ];
      };
      category_candidates: {
        Row: {
          id: string;
          season_id: string;
          category_id: string;
          film_id: string | null;
          work_title: string | null;
          display_label: string;
          identity_key: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          season_id: string;
          category_id: string;
          film_id?: string | null;
          work_title?: string | null;
          display_label: string;
          identity_key: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          season_id?: string;
          category_id?: string;
          film_id?: string | null;
          work_title?: string | null;
          display_label?: string;
          identity_key?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "category_candidates_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_candidates_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_candidates_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      current_aggregate_snapshots: {
        Row: {
          season_id: string;
          category_id: string;
          prediction_intention: Database["public"]["Enums"]["prediction_intention"];
          kind: Database["public"]["Enums"]["aggregate_snapshot_kind"];
          snapshot_id: string;
          published_at: string;
        };
        Insert: {
          season_id: string;
          category_id: string;
          prediction_intention: Database["public"]["Enums"]["prediction_intention"];
          kind: Database["public"]["Enums"]["aggregate_snapshot_kind"];
          snapshot_id: string;
          published_at?: string;
        };
        Update: {
          season_id?: string;
          category_id?: string;
          prediction_intention?: Database["public"]["Enums"]["prediction_intention"];
          kind?: Database["public"]["Enums"]["aggregate_snapshot_kind"];
          snapshot_id?: string;
          published_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "current_aggregate_snapshots_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "current_aggregate_snapshots_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "current_aggregate_snapshots_snapshot_id_fkey";
            columns: ["snapshot_id"];
            isOneToOne: false;
            referencedRelation: "aggregate_snapshots";
            referencedColumns: ["id"];
          },
        ];
      };
      current_official_result_sets: {
        Row: {
          season_id: string;
          kind: Database["public"]["Enums"]["official_result_kind"];
          result_set_id: string;
          published_at: string;
        };
        Insert: {
          season_id: string;
          kind: Database["public"]["Enums"]["official_result_kind"];
          result_set_id: string;
          published_at?: string;
        };
        Update: {
          season_id?: string;
          kind?: Database["public"]["Enums"]["official_result_kind"];
          result_set_id?: string;
          published_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "current_official_result_sets_result_set_id_fkey";
            columns: ["result_set_id"];
            isOneToOne: false;
            referencedRelation: "official_result_sets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "current_official_result_sets_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      film_credit_match_history: {
        Row: {
          id: number;
          film_id: string;
          person_id: string;
          tmdb_credit_id: string;
          role: string;
          department: string | null;
          source_url: string;
          reason: string;
          actor: string;
          created_at: string;
        };
        Insert: {
          id: number;
          film_id: string;
          person_id: string;
          tmdb_credit_id: string;
          role: string;
          department?: string | null;
          source_url: string;
          reason: string;
          actor: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          film_id?: string;
          person_id?: string;
          tmdb_credit_id?: string;
          role?: string;
          department?: string | null;
          source_url?: string;
          reason?: string;
          actor?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "film_credit_match_history_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "film_credit_match_history_person_id_fkey";
            columns: ["person_id"];
            isOneToOne: false;
            referencedRelation: "people";
            referencedColumns: ["id"];
          },
        ];
      };
      film_credits: {
        Row: {
          film_id: string;
          person_id: string;
          tmdb_credit_id: string;
          credit_kind: Database["public"]["Enums"]["film_credit_kind"];
          role: string;
          department: string | null;
          billing_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          film_id: string;
          person_id: string;
          tmdb_credit_id: string;
          credit_kind: Database["public"]["Enums"]["film_credit_kind"];
          role: string;
          department?: string | null;
          billing_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          film_id?: string;
          person_id?: string;
          tmdb_credit_id?: string;
          credit_kind?: Database["public"]["Enums"]["film_credit_kind"];
          role?: string;
          department?: string | null;
          billing_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "film_credits_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "film_credits_person_id_fkey";
            columns: ["person_id"];
            isOneToOne: false;
            referencedRelation: "people";
            referencedColumns: ["id"];
          },
        ];
      };
      film_tmdb_match_history: {
        Row: {
          id: number;
          film_id: string;
          previous_tmdb_id: number | null;
          tmdb_id: number;
          method: Database["public"]["Enums"]["tmdb_match_method"];
          query: string | null;
          reason: string;
          actor: string;
          created_at: string;
        };
        Insert: {
          id: number;
          film_id: string;
          previous_tmdb_id?: number | null;
          tmdb_id: number;
          method: Database["public"]["Enums"]["tmdb_match_method"];
          query?: string | null;
          reason: string;
          actor: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          film_id?: string;
          previous_tmdb_id?: number | null;
          tmdb_id?: number;
          method?: Database["public"]["Enums"]["tmdb_match_method"];
          query?: string | null;
          reason?: string;
          actor?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "film_tmdb_match_history_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "film_tmdb_match_history_previous_tmdb_id_fkey";
            columns: ["previous_tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_movies";
            referencedColumns: ["tmdb_id"];
          },
          {
            foreignKeyName: "film_tmdb_match_history_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_movies";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
      films: {
        Row: {
          id: string;
          title: string;
          alternate_titles: string[];
          eligibility_year: number | null;
          release_status: Database["public"]["Enums"]["film_release_status"];
          release_date: string | null;
          verification_url: string | null;
          notes: string | null;
          tmdb_id: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          title: string;
          alternate_titles?: string[];
          eligibility_year?: number | null;
          release_status?: Database["public"]["Enums"]["film_release_status"];
          release_date?: string | null;
          verification_url?: string | null;
          notes?: string | null;
          tmdb_id?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          alternate_titles?: string[];
          eligibility_year?: number | null;
          release_status?: Database["public"]["Enums"]["film_release_status"];
          release_date?: string | null;
          verification_url?: string | null;
          notes?: string | null;
          tmdb_id?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "films_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_movies";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
      ingestion_review_items: {
        Row: {
          id: number;
          queue_key: string;
          run_id: number;
          connector_id: string;
          observation_id: number | null;
          kind: Database["public"]["Enums"]["ingestion_review_kind"];
          status: Database["public"]["Enums"]["ingestion_review_status"];
          subject_label: string;
          candidate_film_ids: string[];
          candidate_person_ids: string[];
          context: Json;
          resolution_note: string | null;
          resolved_at: string | null;
          resolved_by: string | null;
          created_at: string;
        };
        Insert: {
          id: number;
          queue_key: string;
          run_id: number;
          connector_id: string;
          observation_id?: number | null;
          kind: Database["public"]["Enums"]["ingestion_review_kind"];
          status?: Database["public"]["Enums"]["ingestion_review_status"];
          subject_label: string;
          candidate_film_ids?: string[];
          candidate_person_ids?: string[];
          context?: Json;
          resolution_note?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          queue_key?: string;
          run_id?: number;
          connector_id?: string;
          observation_id?: number | null;
          kind?: Database["public"]["Enums"]["ingestion_review_kind"];
          status?: Database["public"]["Enums"]["ingestion_review_status"];
          subject_label?: string;
          candidate_film_ids?: string[];
          candidate_person_ids?: string[];
          context?: Json;
          resolution_note?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingestion_review_items_connector_id_fkey";
            columns: ["connector_id"];
            isOneToOne: false;
            referencedRelation: "source_connectors";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ingestion_review_items_observation_id_fkey";
            columns: ["observation_id"];
            isOneToOne: false;
            referencedRelation: "professional_observations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ingestion_review_items_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "ingestion_runs";
            referencedColumns: ["id"];
          },
        ];
      };
      ingestion_run_events: {
        Row: {
          id: number;
          run_id: number;
          level: Database["public"]["Enums"]["ingestion_event_level"];
          code: string;
          message: string;
          context: Json;
          created_at: string;
        };
        Insert: {
          id: number;
          run_id: number;
          level: Database["public"]["Enums"]["ingestion_event_level"];
          code: string;
          message: string;
          context?: Json;
          created_at?: string;
        };
        Update: {
          id?: number;
          run_id?: number;
          level?: Database["public"]["Enums"]["ingestion_event_level"];
          code?: string;
          message?: string;
          context?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingestion_run_events_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "ingestion_runs";
            referencedColumns: ["id"];
          },
        ];
      };
      ingestion_runs: {
        Row: {
          id: number;
          run_key: string;
          connector_id: string;
          trigger: Database["public"]["Enums"]["ingestion_trigger"];
          status: Database["public"]["Enums"]["ingestion_run_status"];
          started_at: string;
          finished_at: string | null;
          publications_seen: number;
          observations_seen: number;
          observations_inserted: number;
          observations_duplicate: number;
          review_items_created: number;
          error_summary: string | null;
          created_at: string;
        };
        Insert: {
          id: number;
          run_key: string;
          connector_id: string;
          trigger: Database["public"]["Enums"]["ingestion_trigger"];
          status?: Database["public"]["Enums"]["ingestion_run_status"];
          started_at: string;
          finished_at?: string | null;
          publications_seen?: number;
          observations_seen?: number;
          observations_inserted?: number;
          observations_duplicate?: number;
          review_items_created?: number;
          error_summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          run_key?: string;
          connector_id?: string;
          trigger?: Database["public"]["Enums"]["ingestion_trigger"];
          status?: Database["public"]["Enums"]["ingestion_run_status"];
          started_at?: string;
          finished_at?: string | null;
          publications_seen?: number;
          observations_seen?: number;
          observations_inserted?: number;
          observations_duplicate?: number;
          review_items_created?: number;
          error_summary?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingestion_runs_connector_id_fkey";
            columns: ["connector_id"];
            isOneToOne: false;
            referencedRelation: "source_connectors";
            referencedColumns: ["id"];
          },
        ];
      };
      market_capture_runs: {
        Row: {
          id: number;
          connector_id: string;
          run_key: string;
          status: Database["public"]["Enums"]["ingestion_run_status"];
          started_at: string;
          finished_at: string | null;
          contracts_seen: number;
          snapshots_inserted: number;
          snapshots_duplicate: number;
          error_summary: string | null;
          created_at: string;
        };
        Insert: {
          id: number;
          connector_id: string;
          run_key: string;
          status?: Database["public"]["Enums"]["ingestion_run_status"];
          started_at: string;
          finished_at?: string | null;
          contracts_seen?: number;
          snapshots_inserted?: number;
          snapshots_duplicate?: number;
          error_summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          connector_id?: string;
          run_key?: string;
          status?: Database["public"]["Enums"]["ingestion_run_status"];
          started_at?: string;
          finished_at?: string | null;
          contracts_seen?: number;
          snapshots_inserted?: number;
          snapshots_duplicate?: number;
          error_summary?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "market_capture_runs_connector_id_fkey";
            columns: ["connector_id"];
            isOneToOne: false;
            referencedRelation: "market_connectors";
            referencedColumns: ["id"];
          },
        ];
      };
      market_connectors: {
        Row: {
          id: string;
          source_id: string;
          provider: Database["public"]["Enums"]["market_provider"];
          endpoint_url: string;
          extractor_version: string;
          schedule_cron: string;
          is_active: boolean;
          configuration: Json;
          last_success_at: string | null;
          last_failure_at: string | null;
          last_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          source_id: string;
          provider: Database["public"]["Enums"]["market_provider"];
          endpoint_url: string;
          extractor_version: string;
          schedule_cron?: string;
          is_active?: boolean;
          configuration?: Json;
          last_success_at?: string | null;
          last_failure_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          source_id?: string;
          provider?: Database["public"]["Enums"]["market_provider"];
          endpoint_url?: string;
          extractor_version?: string;
          schedule_cron?: string;
          is_active?: boolean;
          configuration?: Json;
          last_success_at?: string | null;
          last_failure_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "market_connectors_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      market_contracts: {
        Row: {
          id: number;
          provider: Database["public"]["Enums"]["market_provider"];
          source_id: string;
          external_market_id: string;
          external_contract_id: string;
          season_id: string | null;
          category_id: string | null;
          category_candidate_id: string | null;
          market_title: string;
          outcome_label: string;
          source_url: string;
          closes_at: string | null;
          resolved_at: string | null;
          original_data: Json;
          captured_at: string;
          created_at: string;
        };
        Insert: {
          id: number;
          provider: Database["public"]["Enums"]["market_provider"];
          source_id: string;
          external_market_id: string;
          external_contract_id: string;
          season_id?: string | null;
          category_id?: string | null;
          category_candidate_id?: string | null;
          market_title: string;
          outcome_label: string;
          source_url: string;
          closes_at?: string | null;
          resolved_at?: string | null;
          original_data: Json;
          captured_at: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          provider?: Database["public"]["Enums"]["market_provider"];
          source_id?: string;
          external_market_id?: string;
          external_contract_id?: string;
          season_id?: string | null;
          category_id?: string | null;
          category_candidate_id?: string | null;
          market_title?: string;
          outcome_label?: string;
          source_url?: string;
          closes_at?: string | null;
          resolved_at?: string | null;
          original_data?: Json;
          captured_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "market_contracts_category_candidate_id_fkey";
            columns: ["category_candidate_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "market_contracts_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "market_contracts_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "market_contracts_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      market_price_snapshots: {
        Row: {
          id: number;
          contract_id: number;
          run_id: number;
          content_hash: string;
          probability: number | null;
          original_price: number | null;
          original_currency: string | null;
          volume: number | null;
          open_interest: number | null;
          observed_at: string;
          captured_at: string;
          original_data: Json;
          created_at: string;
        };
        Insert: {
          id: number;
          contract_id: number;
          run_id: number;
          content_hash: string;
          probability?: number | null;
          original_price?: number | null;
          original_currency?: string | null;
          volume?: number | null;
          open_interest?: number | null;
          observed_at: string;
          captured_at: string;
          original_data: Json;
          created_at?: string;
        };
        Update: {
          id?: number;
          contract_id?: number;
          run_id?: number;
          content_hash?: string;
          probability?: number | null;
          original_price?: number | null;
          original_currency?: string | null;
          volume?: number | null;
          open_interest?: number | null;
          observed_at?: string;
          captured_at?: string;
          original_data?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "market_price_snapshots_contract_id_fkey";
            columns: ["contract_id"];
            isOneToOne: false;
            referencedRelation: "market_contracts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "market_price_snapshots_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "market_capture_runs";
            referencedColumns: ["id"];
          },
        ];
      };
      official_result_entries: {
        Row: {
          result_set_id: string;
          category_id: string;
          candidate_id: string;
          film_id: string | null;
          person_id: string | null;
          outcome: Database["public"]["Enums"]["official_result_outcome"];
          created_at: string;
          category_candidate_id: string | null;
        };
        Insert: {
          result_set_id: string;
          category_id: string;
          candidate_id: string;
          film_id?: string | null;
          person_id?: string | null;
          outcome: Database["public"]["Enums"]["official_result_outcome"];
          created_at?: string;
          category_candidate_id?: string | null;
        };
        Update: {
          result_set_id?: string;
          category_id?: string;
          candidate_id?: string;
          film_id?: string | null;
          person_id?: string | null;
          outcome?: Database["public"]["Enums"]["official_result_outcome"];
          created_at?: string;
          category_candidate_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "official_result_entries_category_candidate_id_fkey";
            columns: ["category_candidate_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "official_result_entries_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "official_result_entries_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "official_result_entries_person_id_fkey";
            columns: ["person_id"];
            isOneToOne: false;
            referencedRelation: "people";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "official_result_entries_result_set_id_fkey";
            columns: ["result_set_id"];
            isOneToOne: false;
            referencedRelation: "official_result_sets";
            referencedColumns: ["id"];
          },
        ];
      };
      official_result_sets: {
        Row: {
          id: string;
          season_id: string;
          kind: Database["public"]["Enums"]["official_result_kind"];
          source_id: string;
          source_url: string;
          author: string | null;
          published_at: string;
          captured_at: string;
          schema_version: string;
          content_hash: string;
          payload: Json;
          locked_at: string;
          locked_by: string;
          corrects_result_set_id: string | null;
          correction_reason: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          season_id: string;
          kind: Database["public"]["Enums"]["official_result_kind"];
          source_id: string;
          source_url: string;
          author?: string | null;
          published_at: string;
          captured_at: string;
          schema_version: string;
          content_hash: string;
          payload: Json;
          locked_at: string;
          locked_by: string;
          corrects_result_set_id?: string | null;
          correction_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          season_id?: string;
          kind?: Database["public"]["Enums"]["official_result_kind"];
          source_id?: string;
          source_url?: string;
          author?: string | null;
          published_at?: string;
          captured_at?: string;
          schema_version?: string;
          content_hash?: string;
          payload?: Json;
          locked_at?: string;
          locked_by?: string;
          corrects_result_set_id?: string | null;
          correction_reason?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "official_result_sets_corrects_result_set_id_fkey";
            columns: ["corrects_result_set_id"];
            isOneToOne: false;
            referencedRelation: "official_result_sets";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "official_result_sets_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "official_result_sets_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      people: {
        Row: {
          id: string;
          name: string;
          tmdb_id: number;
          created_at: string;
          updated_at: string;
          alternate_names: string[];
        };
        Insert: {
          id: string;
          name: string;
          tmdb_id: number;
          created_at?: string;
          updated_at?: string;
          alternate_names?: string[];
        };
        Update: {
          id?: string;
          name?: string;
          tmdb_id?: number;
          created_at?: string;
          updated_at?: string;
          alternate_names?: string[];
        };
        Relationships: [
          {
            foreignKeyName: "people_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_people";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
      professional_observations: {
        Row: {
          id: number;
          dedupe_key: string;
          source_id: string;
          publication_id: number;
          capture_id: number;
          run_id: number;
          season_id: string;
          film_id: string | null;
          person_id: string | null;
          category_id: string | null;
          data_type: Database["public"]["Enums"]["professional_observation_type"];
          prediction_intention:
            Database["public"]["Enums"]["prediction_intention"] | null;
          original_subject: string;
          original_value: Json;
          original_scale: Json | null;
          source_url: string;
          author: string | null;
          published_at: string | null;
          captured_at: string;
          extractor_version: string;
          participates: boolean;
          state: Database["public"]["Enums"]["professional_observation_state"];
          corrects_observation_id: number | null;
          created_at: string;
          category_candidate_id: string | null;
        };
        Insert: {
          id: number;
          dedupe_key: string;
          source_id: string;
          publication_id: number;
          capture_id: number;
          run_id: number;
          season_id: string;
          film_id?: string | null;
          person_id?: string | null;
          category_id?: string | null;
          data_type: Database["public"]["Enums"]["professional_observation_type"];
          prediction_intention?:
            Database["public"]["Enums"]["prediction_intention"] | null;
          original_subject: string;
          original_value: Json;
          original_scale?: Json | null;
          source_url: string;
          author?: string | null;
          published_at?: string | null;
          captured_at: string;
          extractor_version: string;
          participates?: boolean;
          state?: Database["public"]["Enums"]["professional_observation_state"];
          corrects_observation_id?: number | null;
          created_at?: string;
          category_candidate_id?: string | null;
        };
        Update: {
          id?: number;
          dedupe_key?: string;
          source_id?: string;
          publication_id?: number;
          capture_id?: number;
          run_id?: number;
          season_id?: string;
          film_id?: string | null;
          person_id?: string | null;
          category_id?: string | null;
          data_type?: Database["public"]["Enums"]["professional_observation_type"];
          prediction_intention?:
            Database["public"]["Enums"]["prediction_intention"] | null;
          original_subject?: string;
          original_value?: Json;
          original_scale?: Json | null;
          source_url?: string;
          author?: string | null;
          published_at?: string | null;
          captured_at?: string;
          extractor_version?: string;
          participates?: boolean;
          state?: Database["public"]["Enums"]["professional_observation_state"];
          corrects_observation_id?: number | null;
          created_at?: string;
          category_candidate_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "professional_observations_capture_id_fkey";
            columns: ["capture_id"];
            isOneToOne: false;
            referencedRelation: "source_publication_captures";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_category_candidate_id_fkey";
            columns: ["category_candidate_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_corrects_observation_id_fkey";
            columns: ["corrects_observation_id"];
            isOneToOne: false;
            referencedRelation: "professional_observations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_person_id_fkey";
            columns: ["person_id"];
            isOneToOne: false;
            referencedRelation: "people";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "source_publications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "ingestion_runs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      season_categories: {
        Row: {
          season_id: string;
          category_id: string;
          is_enabled: boolean;
          created_at: string;
        };
        Insert: {
          season_id: string;
          category_id: string;
          is_enabled?: boolean;
          created_at?: string;
        };
        Update: {
          season_id?: string;
          category_id?: string;
          is_enabled?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "season_categories_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "season_categories_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      season_films: {
        Row: {
          season_id: string;
          film_id: string;
          created_at: string;
        };
        Insert: {
          season_id: string;
          film_id: string;
          created_at?: string;
        };
        Update: {
          season_id?: string;
          film_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "season_films_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "season_films_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      seasons: {
        Row: {
          id: string;
          ceremony_year: number;
          eligibility_year: number | null;
          eligibility_period: string | null;
          opens_on: string | null;
          closes_on: string | null;
          nominations_announced_on: string | null;
          ceremony_on: string | null;
          status: Database["public"]["Enums"]["season_status"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          ceremony_year: number;
          eligibility_year?: number | null;
          eligibility_period?: string | null;
          opens_on?: string | null;
          closes_on?: string | null;
          nominations_announced_on?: string | null;
          ceremony_on?: string | null;
          status?: Database["public"]["Enums"]["season_status"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ceremony_year?: number;
          eligibility_year?: number | null;
          eligibility_period?: string | null;
          opens_on?: string | null;
          closes_on?: string | null;
          nominations_announced_on?: string | null;
          ceremony_on?: string | null;
          status?: Database["public"]["Enums"]["season_status"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      snapshot_observations: {
        Row: {
          snapshot_id: string;
          observation_id: number;
          role: Database["public"]["Enums"]["snapshot_observation_role"];
          created_at: string;
        };
        Insert: {
          snapshot_id: string;
          observation_id: number;
          role: Database["public"]["Enums"]["snapshot_observation_role"];
          created_at?: string;
        };
        Update: {
          snapshot_id?: string;
          observation_id?: number;
          role?: Database["public"]["Enums"]["snapshot_observation_role"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "snapshot_observations_observation_id_fkey";
            columns: ["observation_id"];
            isOneToOne: false;
            referencedRelation: "professional_observations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "snapshot_observations_snapshot_id_fkey";
            columns: ["snapshot_id"];
            isOneToOne: false;
            referencedRelation: "aggregate_snapshots";
            referencedColumns: ["id"];
          },
        ];
      };
      snapshot_schedules: {
        Row: {
          id: string;
          season_id: string;
          category_id: string;
          prediction_intention: Database["public"]["Enums"]["prediction_intention"];
          kind: Database["public"]["Enums"]["aggregate_snapshot_kind"];
          cron_expression: string;
          time_zone: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          season_id: string;
          category_id: string;
          prediction_intention: Database["public"]["Enums"]["prediction_intention"];
          kind?: Database["public"]["Enums"]["aggregate_snapshot_kind"];
          cron_expression: string;
          time_zone?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          season_id?: string;
          category_id?: string;
          prediction_intention?: Database["public"]["Enums"]["prediction_intention"];
          kind?: Database["public"]["Enums"]["aggregate_snapshot_kind"];
          cron_expression?: string;
          time_zone?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "snapshot_schedules_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "snapshot_schedules_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      source_connectors: {
        Row: {
          id: string;
          source_id: string | null;
          name: string;
          kind: Database["public"]["Enums"]["connector_kind"];
          endpoint_url: string | null;
          extractor_version: string;
          is_active: boolean;
          schedule_cron: string | null;
          configuration: Json;
          last_success_at: string | null;
          last_failure_at: string | null;
          last_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          source_id?: string | null;
          name: string;
          kind: Database["public"]["Enums"]["connector_kind"];
          endpoint_url?: string | null;
          extractor_version: string;
          is_active?: boolean;
          schedule_cron?: string | null;
          configuration?: Json;
          last_success_at?: string | null;
          last_failure_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          source_id?: string | null;
          name?: string;
          kind?: Database["public"]["Enums"]["connector_kind"];
          endpoint_url?: string | null;
          extractor_version?: string;
          is_active?: boolean;
          schedule_cron?: string | null;
          configuration?: Json;
          last_success_at?: string | null;
          last_failure_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "source_connectors_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      source_publication_captures: {
        Row: {
          id: number;
          publication_id: number;
          content_hash: string;
          source_url: string;
          original_data: Json;
          captured_at: string;
          extractor_version: string;
          created_at: string;
        };
        Insert: {
          id: number;
          publication_id: number;
          content_hash: string;
          source_url: string;
          original_data: Json;
          captured_at: string;
          extractor_version: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          publication_id?: number;
          content_hash?: string;
          source_url?: string;
          original_data?: Json;
          captured_at?: string;
          extractor_version?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "source_publication_captures_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "source_publications";
            referencedColumns: ["id"];
          },
        ];
      };
      source_publications: {
        Row: {
          id: number;
          source_id: string;
          external_id: string;
          canonical_url: string;
          title: string;
          author: string | null;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: number;
          source_id: string;
          external_id: string;
          canonical_url: string;
          title: string;
          author?: string | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          source_id?: string;
          external_id?: string;
          canonical_url?: string;
          title?: string;
          author?: string | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "source_publications_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      sources: {
        Row: {
          id: string;
          name: string;
          source_types: string[];
          homepage_url: string;
          editorial_status: Database["public"]["Enums"]["source_editorial_status"];
          technical_status: Database["public"]["Enums"]["source_technical_status"];
          publication_status: Database["public"]["Enums"]["source_publication_status"];
          last_reviewed_on: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          source_types: string[];
          homepage_url: string;
          editorial_status: Database["public"]["Enums"]["source_editorial_status"];
          technical_status: Database["public"]["Enums"]["source_technical_status"];
          publication_status: Database["public"]["Enums"]["source_publication_status"];
          last_reviewed_on?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          source_types?: string[];
          homepage_url?: string;
          editorial_status?: Database["public"]["Enums"]["source_editorial_status"];
          technical_status?: Database["public"]["Enums"]["source_technical_status"];
          publication_status?: Database["public"]["Enums"]["source_publication_status"];
          last_reviewed_on?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tmdb_movie_snapshots: {
        Row: {
          id: number;
          tmdb_id: number;
          locale: string;
          content_hash: string;
          title: string;
          original_title: string;
          original_language: string | null;
          overview: string | null;
          release_date: string | null;
          runtime: number | null;
          status: string | null;
          tagline: string | null;
          imdb_id: string | null;
          poster_path: string | null;
          backdrop_path: string | null;
          genres: Json;
          original_data: Json;
          source_url: string;
          fetched_at: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id: number;
          tmdb_id: number;
          locale: string;
          content_hash: string;
          title: string;
          original_title: string;
          original_language?: string | null;
          overview?: string | null;
          release_date?: string | null;
          runtime?: number | null;
          status?: string | null;
          tagline?: string | null;
          imdb_id?: string | null;
          poster_path?: string | null;
          backdrop_path?: string | null;
          genres?: Json;
          original_data: Json;
          source_url: string;
          fetched_at: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          tmdb_id?: number;
          locale?: string;
          content_hash?: string;
          title?: string;
          original_title?: string;
          original_language?: string | null;
          overview?: string | null;
          release_date?: string | null;
          runtime?: number | null;
          status?: string | null;
          tagline?: string | null;
          imdb_id?: string | null;
          poster_path?: string | null;
          backdrop_path?: string | null;
          genres?: Json;
          original_data?: Json;
          source_url?: string;
          fetched_at?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tmdb_movie_snapshots_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_movies";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
      tmdb_movies: {
        Row: {
          tmdb_id: number;
          last_checked_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          tmdb_id: number;
          last_checked_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tmdb_id?: number;
          last_checked_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tmdb_people: {
        Row: {
          tmdb_id: number;
          last_checked_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          tmdb_id: number;
          last_checked_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tmdb_id?: number;
          last_checked_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tmdb_person_snapshots: {
        Row: {
          id: number;
          tmdb_id: number;
          locale: string;
          content_hash: string;
          name: string;
          original_name: string | null;
          known_for_department: string | null;
          biography: string | null;
          birthday: string | null;
          deathday: string | null;
          place_of_birth: string | null;
          homepage_url: string | null;
          imdb_id: string | null;
          profile_path: string | null;
          original_data: Json;
          source_url: string;
          fetched_at: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id: number;
          tmdb_id: number;
          locale: string;
          content_hash: string;
          name: string;
          original_name?: string | null;
          known_for_department?: string | null;
          biography?: string | null;
          birthday?: string | null;
          deathday?: string | null;
          place_of_birth?: string | null;
          homepage_url?: string | null;
          imdb_id?: string | null;
          profile_path?: string | null;
          original_data: Json;
          source_url: string;
          fetched_at: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          tmdb_id?: number;
          locale?: string;
          content_hash?: string;
          name?: string;
          original_name?: string | null;
          known_for_department?: string | null;
          biography?: string | null;
          birthday?: string | null;
          deathday?: string | null;
          place_of_birth?: string | null;
          homepage_url?: string | null;
          imdb_id?: string | null;
          profile_path?: string | null;
          original_data?: Json;
          source_url?: string;
          fetched_at?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tmdb_person_snapshots_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_people";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
      user_film_states: {
        Row: {
          user_id: string;
          film_id: string;
          watched_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          film_id: string;
          watched_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          film_id?: string;
          watched_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_film_states_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_film_states_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "user_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
      user_profiles: {
        Row: {
          user_id: string;
          slug: string;
          display_name: string;
          is_public: boolean;
          watched_is_public: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          slug: string;
          display_name: string;
          is_public?: boolean;
          watched_is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          slug?: string;
          display_name?: string;
          is_public?: boolean;
          watched_is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_profiles_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      user_ranking_entries: {
        Row: {
          ranking_id: string;
          user_id: string;
          season_id: string;
          category_id: string;
          category_candidate_id: string;
          position: number;
          created_at: string;
        };
        Insert: {
          ranking_id: string;
          user_id: string;
          season_id: string;
          category_id: string;
          category_candidate_id: string;
          position: number;
          created_at?: string;
        };
        Update: {
          ranking_id?: string;
          user_id?: string;
          season_id?: string;
          category_id?: string;
          category_candidate_id?: string;
          position?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_ranking_entries_candidate_scope_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_ranking_entries_candidate_scope_fkey";
            columns: ["category_candidate_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["category_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_candidate_scope_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["category_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_candidate_scope_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["category_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_candidate_scope_fkey";
            columns: ["category_candidate_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_ranking_entries_candidate_scope_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_ranking_entries_candidate_scope_fkey";
            columns: ["category_candidate_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["season_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_candidate_scope_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["season_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_candidate_scope_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "category_candidates";
            referencedColumns: ["season_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["ranking_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["season_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["season_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["season_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["season_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["ranking_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["user_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["category_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["category_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["category_id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["ranking_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "user_ranking_entries_ranking_scope_fkey";
            columns: ["ranking_id"];
            isOneToOne: false;
            referencedRelation: "user_rankings";
            referencedColumns: ["category_id"];
          },
        ];
      };
      user_rankings: {
        Row: {
          id: string;
          user_id: string;
          season_id: string;
          category_id: string;
          is_public: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          season_id: string;
          category_id: string;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          season_id?: string;
          category_id?: string;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_rankings_season_category_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "season_categories";
            referencedColumns: ["category_id"];
          },
          {
            foreignKeyName: "user_rankings_season_category_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "season_categories";
            referencedColumns: ["category_id"];
          },
          {
            foreignKeyName: "user_rankings_season_category_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "season_categories";
            referencedColumns: ["season_id"];
          },
          {
            foreignKeyName: "user_rankings_season_category_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "season_categories";
            referencedColumns: ["season_id"];
          },
          {
            foreignKeyName: "user_rankings_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "user_profiles";
            referencedColumns: ["user_id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      save_my_ranking: {
        Args: {
          ranking_season_id: string;
          ranking_category_id: string;
          ranking_candidate_ids: string[];
          ranking_is_public: boolean;
        };
        Returns: string;
      };
      set_updated_at: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
    };
    Enums: {
      aggregate_snapshot_kind: "periodic" | "nomination_final" | "winner_final";
      category_subject: "film" | "person";
      connector_kind: "api_json" | "rss" | "html" | "manual";
      film_credit_kind: "cast" | "crew";
      film_release_status: "announced" | "upcoming" | "released";
      ingestion_event_level: "info" | "warning" | "error";
      ingestion_review_kind:
        "film_match" | "person_match" | "category_match" | "invalid_value";
      ingestion_review_status: "pending" | "resolved" | "dismissed";
      ingestion_run_status: "running" | "succeeded" | "partial" | "failed";
      ingestion_trigger: "manual" | "scheduled" | "fixture";
      market_provider: "kalshi" | "polymarket";
      official_result_kind: "nominations" | "winners";
      official_result_outcome: "nominee" | "winner";
      prediction_intention: "nomination" | "winner";
      professional_observation_state:
        "pending_review" | "published" | "corrected" | "excluded";
      professional_observation_type:
        | "review"
        | "score_individual"
        | "score_aggregate"
        | "prediction_ordered"
        | "prediction_selection";
      season_status:
        "preparation" | "active" | "nominations_announced" | "closed";
      snapshot_observation_role: "included" | "excluded";
      source_editorial_status:
        "candidate" | "sampled" | "selected" | "paused" | "rejected";
      source_publication_status:
        | "not-reviewed"
        | "review-before-publish"
        | "publishable"
        | "replace-before-publish";
      source_technical_status:
        "manual" | "prototype" | "automated" | "failing" | "retired";
      tmdb_match_method: "search_exact" | "manual" | "correction";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
