// Generated by scripts/generate-database-types.mjs.
// Source: versioned SQL migrations in supabase/migrations.
// Do not edit this file manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      categories: {
        Row: {
          id: string;
          name: string;
          subject: Database["public"]["Enums"]["category_subject"];
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          subject: Database["public"]["Enums"]["category_subject"];
          display_order: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          subject?: Database["public"]["Enums"]["category_subject"];
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      film_credits: {
        Row: {
          film_id: string;
          person_id: string;
          tmdb_credit_id: string;
          credit_kind: Database["public"]["Enums"]["film_credit_kind"];
          role: string;
          department: string | null;
          billing_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          film_id: string;
          person_id: string;
          tmdb_credit_id: string;
          credit_kind: Database["public"]["Enums"]["film_credit_kind"];
          role: string;
          department?: string | null;
          billing_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          film_id?: string;
          person_id?: string;
          tmdb_credit_id?: string;
          credit_kind?: Database["public"]["Enums"]["film_credit_kind"];
          role?: string;
          department?: string | null;
          billing_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "film_credits_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "film_credits_person_id_fkey";
            columns: ["person_id"];
            isOneToOne: false;
            referencedRelation: "people";
            referencedColumns: ["id"];
          },
        ];
      };
      film_tmdb_match_history: {
        Row: {
          id: number;
          film_id: string;
          previous_tmdb_id: number | null;
          tmdb_id: number;
          method: Database["public"]["Enums"]["tmdb_match_method"];
          query: string | null;
          reason: string;
          actor: string;
          created_at: string;
        };
        Insert: {
          id: number;
          film_id: string;
          previous_tmdb_id?: number | null;
          tmdb_id: number;
          method: Database["public"]["Enums"]["tmdb_match_method"];
          query?: string | null;
          reason: string;
          actor: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          film_id?: string;
          previous_tmdb_id?: number | null;
          tmdb_id?: number;
          method?: Database["public"]["Enums"]["tmdb_match_method"];
          query?: string | null;
          reason?: string;
          actor?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "film_tmdb_match_history_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "film_tmdb_match_history_previous_tmdb_id_fkey";
            columns: ["previous_tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_movies";
            referencedColumns: ["tmdb_id"];
          },
          {
            foreignKeyName: "film_tmdb_match_history_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_movies";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
      films: {
        Row: {
          id: string;
          title: string;
          alternate_titles: string[];
          eligibility_year: number | null;
          release_status: Database["public"]["Enums"]["film_release_status"];
          release_date: string | null;
          verification_url: string | null;
          notes: string | null;
          tmdb_id: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          title: string;
          alternate_titles?: string[];
          eligibility_year?: number | null;
          release_status?: Database["public"]["Enums"]["film_release_status"];
          release_date?: string | null;
          verification_url?: string | null;
          notes?: string | null;
          tmdb_id?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          alternate_titles?: string[];
          eligibility_year?: number | null;
          release_status?: Database["public"]["Enums"]["film_release_status"];
          release_date?: string | null;
          verification_url?: string | null;
          notes?: string | null;
          tmdb_id?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "films_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_movies";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
      ingestion_review_items: {
        Row: {
          id: number;
          queue_key: string;
          run_id: number;
          connector_id: string;
          observation_id: number | null;
          kind: Database["public"]["Enums"]["ingestion_review_kind"];
          status: Database["public"]["Enums"]["ingestion_review_status"];
          subject_label: string;
          candidate_film_ids: string[];
          candidate_person_ids: string[];
          context: Json;
          resolution_note: string | null;
          resolved_at: string | null;
          resolved_by: string | null;
          created_at: string;
        };
        Insert: {
          id: number;
          queue_key: string;
          run_id: number;
          connector_id: string;
          observation_id?: number | null;
          kind: Database["public"]["Enums"]["ingestion_review_kind"];
          status?: Database["public"]["Enums"]["ingestion_review_status"];
          subject_label: string;
          candidate_film_ids?: string[];
          candidate_person_ids?: string[];
          context?: Json;
          resolution_note?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          queue_key?: string;
          run_id?: number;
          connector_id?: string;
          observation_id?: number | null;
          kind?: Database["public"]["Enums"]["ingestion_review_kind"];
          status?: Database["public"]["Enums"]["ingestion_review_status"];
          subject_label?: string;
          candidate_film_ids?: string[];
          candidate_person_ids?: string[];
          context?: Json;
          resolution_note?: string | null;
          resolved_at?: string | null;
          resolved_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingestion_review_items_connector_id_fkey";
            columns: ["connector_id"];
            isOneToOne: false;
            referencedRelation: "source_connectors";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ingestion_review_items_observation_id_fkey";
            columns: ["observation_id"];
            isOneToOne: false;
            referencedRelation: "professional_observations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ingestion_review_items_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "ingestion_runs";
            referencedColumns: ["id"];
          },
        ];
      };
      ingestion_run_events: {
        Row: {
          id: number;
          run_id: number;
          level: Database["public"]["Enums"]["ingestion_event_level"];
          code: string;
          message: string;
          context: Json;
          created_at: string;
        };
        Insert: {
          id: number;
          run_id: number;
          level: Database["public"]["Enums"]["ingestion_event_level"];
          code: string;
          message: string;
          context?: Json;
          created_at?: string;
        };
        Update: {
          id?: number;
          run_id?: number;
          level?: Database["public"]["Enums"]["ingestion_event_level"];
          code?: string;
          message?: string;
          context?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingestion_run_events_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "ingestion_runs";
            referencedColumns: ["id"];
          },
        ];
      };
      ingestion_runs: {
        Row: {
          id: number;
          run_key: string;
          connector_id: string;
          trigger: Database["public"]["Enums"]["ingestion_trigger"];
          status: Database["public"]["Enums"]["ingestion_run_status"];
          started_at: string;
          finished_at: string | null;
          publications_seen: number;
          observations_seen: number;
          observations_inserted: number;
          observations_duplicate: number;
          review_items_created: number;
          error_summary: string | null;
          created_at: string;
        };
        Insert: {
          id: number;
          run_key: string;
          connector_id: string;
          trigger: Database["public"]["Enums"]["ingestion_trigger"];
          status?: Database["public"]["Enums"]["ingestion_run_status"];
          started_at: string;
          finished_at?: string | null;
          publications_seen?: number;
          observations_seen?: number;
          observations_inserted?: number;
          observations_duplicate?: number;
          review_items_created?: number;
          error_summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          run_key?: string;
          connector_id?: string;
          trigger?: Database["public"]["Enums"]["ingestion_trigger"];
          status?: Database["public"]["Enums"]["ingestion_run_status"];
          started_at?: string;
          finished_at?: string | null;
          publications_seen?: number;
          observations_seen?: number;
          observations_inserted?: number;
          observations_duplicate?: number;
          review_items_created?: number;
          error_summary?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ingestion_runs_connector_id_fkey";
            columns: ["connector_id"];
            isOneToOne: false;
            referencedRelation: "source_connectors";
            referencedColumns: ["id"];
          },
        ];
      };
      people: {
        Row: {
          id: string;
          name: string;
          tmdb_id: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          tmdb_id: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          tmdb_id?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "people_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_people";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
      professional_observations: {
        Row: {
          id: number;
          dedupe_key: string;
          source_id: string;
          publication_id: number;
          capture_id: number;
          run_id: number;
          season_id: string;
          film_id: string | null;
          person_id: string | null;
          category_id: string | null;
          data_type: Database["public"]["Enums"]["professional_observation_type"];
          prediction_intention:
            Database["public"]["Enums"]["prediction_intention"] | null;
          original_subject: string;
          original_value: Json;
          original_scale: Json | null;
          source_url: string;
          author: string | null;
          published_at: string | null;
          captured_at: string;
          extractor_version: string;
          participates: boolean;
          state: Database["public"]["Enums"]["professional_observation_state"];
          corrects_observation_id: number | null;
          created_at: string;
        };
        Insert: {
          id: number;
          dedupe_key: string;
          source_id: string;
          publication_id: number;
          capture_id: number;
          run_id: number;
          season_id: string;
          film_id?: string | null;
          person_id?: string | null;
          category_id?: string | null;
          data_type: Database["public"]["Enums"]["professional_observation_type"];
          prediction_intention?:
            Database["public"]["Enums"]["prediction_intention"] | null;
          original_subject: string;
          original_value: Json;
          original_scale?: Json | null;
          source_url: string;
          author?: string | null;
          published_at?: string | null;
          captured_at: string;
          extractor_version: string;
          participates?: boolean;
          state?: Database["public"]["Enums"]["professional_observation_state"];
          corrects_observation_id?: number | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          dedupe_key?: string;
          source_id?: string;
          publication_id?: number;
          capture_id?: number;
          run_id?: number;
          season_id?: string;
          film_id?: string | null;
          person_id?: string | null;
          category_id?: string | null;
          data_type?: Database["public"]["Enums"]["professional_observation_type"];
          prediction_intention?:
            Database["public"]["Enums"]["prediction_intention"] | null;
          original_subject?: string;
          original_value?: Json;
          original_scale?: Json | null;
          source_url?: string;
          author?: string | null;
          published_at?: string | null;
          captured_at?: string;
          extractor_version?: string;
          participates?: boolean;
          state?: Database["public"]["Enums"]["professional_observation_state"];
          corrects_observation_id?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "professional_observations_capture_id_fkey";
            columns: ["capture_id"];
            isOneToOne: false;
            referencedRelation: "source_publication_captures";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_corrects_observation_id_fkey";
            columns: ["corrects_observation_id"];
            isOneToOne: false;
            referencedRelation: "professional_observations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_person_id_fkey";
            columns: ["person_id"];
            isOneToOne: false;
            referencedRelation: "people";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "source_publications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "ingestion_runs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "professional_observations_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      season_categories: {
        Row: {
          season_id: string;
          category_id: string;
          is_enabled: boolean;
          created_at: string;
        };
        Insert: {
          season_id: string;
          category_id: string;
          is_enabled?: boolean;
          created_at?: string;
        };
        Update: {
          season_id?: string;
          category_id?: string;
          is_enabled?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "season_categories_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "season_categories_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      season_films: {
        Row: {
          season_id: string;
          film_id: string;
          created_at: string;
        };
        Insert: {
          season_id: string;
          film_id: string;
          created_at?: string;
        };
        Update: {
          season_id?: string;
          film_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "season_films_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "season_films_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      seasons: {
        Row: {
          id: string;
          ceremony_year: number;
          eligibility_year: number | null;
          eligibility_period: string | null;
          opens_on: string | null;
          closes_on: string | null;
          nominations_announced_on: string | null;
          ceremony_on: string | null;
          status: Database["public"]["Enums"]["season_status"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          ceremony_year: number;
          eligibility_year?: number | null;
          eligibility_period?: string | null;
          opens_on?: string | null;
          closes_on?: string | null;
          nominations_announced_on?: string | null;
          ceremony_on?: string | null;
          status?: Database["public"]["Enums"]["season_status"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ceremony_year?: number;
          eligibility_year?: number | null;
          eligibility_period?: string | null;
          opens_on?: string | null;
          closes_on?: string | null;
          nominations_announced_on?: string | null;
          ceremony_on?: string | null;
          status?: Database["public"]["Enums"]["season_status"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      source_connectors: {
        Row: {
          id: string;
          source_id: string | null;
          name: string;
          kind: Database["public"]["Enums"]["connector_kind"];
          endpoint_url: string | null;
          extractor_version: string;
          is_active: boolean;
          schedule_cron: string | null;
          configuration: Json;
          last_success_at: string | null;
          last_failure_at: string | null;
          last_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          source_id?: string | null;
          name: string;
          kind: Database["public"]["Enums"]["connector_kind"];
          endpoint_url?: string | null;
          extractor_version: string;
          is_active?: boolean;
          schedule_cron?: string | null;
          configuration?: Json;
          last_success_at?: string | null;
          last_failure_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          source_id?: string | null;
          name?: string;
          kind?: Database["public"]["Enums"]["connector_kind"];
          endpoint_url?: string | null;
          extractor_version?: string;
          is_active?: boolean;
          schedule_cron?: string | null;
          configuration?: Json;
          last_success_at?: string | null;
          last_failure_at?: string | null;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "source_connectors_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      source_publication_captures: {
        Row: {
          id: number;
          publication_id: number;
          content_hash: string;
          source_url: string;
          original_data: Json;
          captured_at: string;
          extractor_version: string;
          created_at: string;
        };
        Insert: {
          id: number;
          publication_id: number;
          content_hash: string;
          source_url: string;
          original_data: Json;
          captured_at: string;
          extractor_version: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          publication_id?: number;
          content_hash?: string;
          source_url?: string;
          original_data?: Json;
          captured_at?: string;
          extractor_version?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "source_publication_captures_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "source_publications";
            referencedColumns: ["id"];
          },
        ];
      };
      source_publications: {
        Row: {
          id: number;
          source_id: string;
          external_id: string;
          canonical_url: string;
          title: string;
          author: string | null;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: number;
          source_id: string;
          external_id: string;
          canonical_url: string;
          title: string;
          author?: string | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          source_id?: string;
          external_id?: string;
          canonical_url?: string;
          title?: string;
          author?: string | null;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "source_publications_source_id_fkey";
            columns: ["source_id"];
            isOneToOne: false;
            referencedRelation: "sources";
            referencedColumns: ["id"];
          },
        ];
      };
      sources: {
        Row: {
          id: string;
          name: string;
          source_types: string[];
          homepage_url: string;
          editorial_status: Database["public"]["Enums"]["source_editorial_status"];
          technical_status: Database["public"]["Enums"]["source_technical_status"];
          publication_status: Database["public"]["Enums"]["source_publication_status"];
          last_reviewed_on: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          source_types: string[];
          homepage_url: string;
          editorial_status: Database["public"]["Enums"]["source_editorial_status"];
          technical_status: Database["public"]["Enums"]["source_technical_status"];
          publication_status: Database["public"]["Enums"]["source_publication_status"];
          last_reviewed_on?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          source_types?: string[];
          homepage_url?: string;
          editorial_status?: Database["public"]["Enums"]["source_editorial_status"];
          technical_status?: Database["public"]["Enums"]["source_technical_status"];
          publication_status?: Database["public"]["Enums"]["source_publication_status"];
          last_reviewed_on?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tmdb_movie_snapshots: {
        Row: {
          id: number;
          tmdb_id: number;
          locale: string;
          content_hash: string;
          title: string;
          original_title: string;
          original_language: string | null;
          overview: string | null;
          release_date: string | null;
          runtime: number | null;
          status: string | null;
          tagline: string | null;
          imdb_id: string | null;
          poster_path: string | null;
          backdrop_path: string | null;
          genres: Json;
          original_data: Json;
          source_url: string;
          fetched_at: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id: number;
          tmdb_id: number;
          locale: string;
          content_hash: string;
          title: string;
          original_title: string;
          original_language?: string | null;
          overview?: string | null;
          release_date?: string | null;
          runtime?: number | null;
          status?: string | null;
          tagline?: string | null;
          imdb_id?: string | null;
          poster_path?: string | null;
          backdrop_path?: string | null;
          genres?: Json;
          original_data: Json;
          source_url: string;
          fetched_at: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          tmdb_id?: number;
          locale?: string;
          content_hash?: string;
          title?: string;
          original_title?: string;
          original_language?: string | null;
          overview?: string | null;
          release_date?: string | null;
          runtime?: number | null;
          status?: string | null;
          tagline?: string | null;
          imdb_id?: string | null;
          poster_path?: string | null;
          backdrop_path?: string | null;
          genres?: Json;
          original_data?: Json;
          source_url?: string;
          fetched_at?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tmdb_movie_snapshots_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_movies";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
      tmdb_movies: {
        Row: {
          tmdb_id: number;
          last_checked_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          tmdb_id: number;
          last_checked_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tmdb_id?: number;
          last_checked_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tmdb_people: {
        Row: {
          tmdb_id: number;
          last_checked_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          tmdb_id: number;
          last_checked_at: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tmdb_id?: number;
          last_checked_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tmdb_person_snapshots: {
        Row: {
          id: number;
          tmdb_id: number;
          locale: string;
          content_hash: string;
          name: string;
          original_name: string | null;
          known_for_department: string | null;
          biography: string | null;
          birthday: string | null;
          deathday: string | null;
          place_of_birth: string | null;
          homepage_url: string | null;
          imdb_id: string | null;
          profile_path: string | null;
          original_data: Json;
          source_url: string;
          fetched_at: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id: number;
          tmdb_id: number;
          locale: string;
          content_hash: string;
          name: string;
          original_name?: string | null;
          known_for_department?: string | null;
          biography?: string | null;
          birthday?: string | null;
          deathday?: string | null;
          place_of_birth?: string | null;
          homepage_url?: string | null;
          imdb_id?: string | null;
          profile_path?: string | null;
          original_data: Json;
          source_url: string;
          fetched_at: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          tmdb_id?: number;
          locale?: string;
          content_hash?: string;
          name?: string;
          original_name?: string | null;
          known_for_department?: string | null;
          biography?: string | null;
          birthday?: string | null;
          deathday?: string | null;
          place_of_birth?: string | null;
          homepage_url?: string | null;
          imdb_id?: string | null;
          profile_path?: string | null;
          original_data?: Json;
          source_url?: string;
          fetched_at?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tmdb_person_snapshots_tmdb_id_fkey";
            columns: ["tmdb_id"];
            isOneToOne: false;
            referencedRelation: "tmdb_people";
            referencedColumns: ["tmdb_id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      set_updated_at: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
    };
    Enums: {
      category_subject: "film" | "person";
      connector_kind: "api_json" | "rss" | "html" | "manual";
      film_credit_kind: "cast" | "crew";
      film_release_status: "announced" | "upcoming" | "released";
      ingestion_event_level: "info" | "warning" | "error";
      ingestion_review_kind:
        "film_match" | "person_match" | "category_match" | "invalid_value";
      ingestion_review_status: "pending" | "resolved" | "dismissed";
      ingestion_run_status: "running" | "succeeded" | "partial" | "failed";
      ingestion_trigger: "manual" | "scheduled" | "fixture";
      prediction_intention: "nomination" | "winner";
      professional_observation_state:
        "pending_review" | "published" | "corrected" | "excluded";
      professional_observation_type:
        | "review"
        | "score_individual"
        | "score_aggregate"
        | "prediction_ordered"
        | "prediction_selection";
      season_status:
        "preparation" | "active" | "nominations_announced" | "closed";
      source_editorial_status:
        "candidate" | "sampled" | "selected" | "paused" | "rejected";
      source_publication_status:
        | "not-reviewed"
        | "review-before-publish"
        | "publishable"
        | "replace-before-publish";
      source_technical_status:
        "manual" | "prototype" | "automated" | "failing" | "retired";
      tmdb_match_method: "search_exact" | "manual" | "correction";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
