// Generated by scripts/generate-database-types.mjs.
// Source: versioned SQL migrations in supabase/migrations.
// Do not edit this file manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      categories: {
        Row: {
          id: string;
          name: string;
          subject: Database["public"]["Enums"]["category_subject"];
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          subject: Database["public"]["Enums"]["category_subject"];
          display_order: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          subject?: Database["public"]["Enums"]["category_subject"];
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      films: {
        Row: {
          id: string;
          title: string;
          alternate_titles: string[];
          eligibility_year: number | null;
          release_status: Database["public"]["Enums"]["film_release_status"];
          release_date: string | null;
          verification_url: string | null;
          notes: string | null;
          tmdb_id: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          title: string;
          alternate_titles?: string[];
          eligibility_year?: number | null;
          release_status?: Database["public"]["Enums"]["film_release_status"];
          release_date?: string | null;
          verification_url?: string | null;
          notes?: string | null;
          tmdb_id?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          alternate_titles?: string[];
          eligibility_year?: number | null;
          release_status?: Database["public"]["Enums"]["film_release_status"];
          release_date?: string | null;
          verification_url?: string | null;
          notes?: string | null;
          tmdb_id?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      season_categories: {
        Row: {
          season_id: string;
          category_id: string;
          is_enabled: boolean;
          created_at: string;
        };
        Insert: {
          season_id: string;
          category_id: string;
          is_enabled?: boolean;
          created_at?: string;
        };
        Update: {
          season_id?: string;
          category_id?: string;
          is_enabled?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "season_categories_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "season_categories_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      season_films: {
        Row: {
          season_id: string;
          film_id: string;
          created_at: string;
        };
        Insert: {
          season_id: string;
          film_id: string;
          created_at?: string;
        };
        Update: {
          season_id?: string;
          film_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "season_films_film_id_fkey";
            columns: ["film_id"];
            isOneToOne: false;
            referencedRelation: "films";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "season_films_season_id_fkey";
            columns: ["season_id"];
            isOneToOne: false;
            referencedRelation: "seasons";
            referencedColumns: ["id"];
          },
        ];
      };
      seasons: {
        Row: {
          id: string;
          ceremony_year: number;
          eligibility_year: number | null;
          eligibility_period: string | null;
          opens_on: string | null;
          closes_on: string | null;
          nominations_announced_on: string | null;
          ceremony_on: string | null;
          status: Database["public"]["Enums"]["season_status"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          ceremony_year: number;
          eligibility_year?: number | null;
          eligibility_period?: string | null;
          opens_on?: string | null;
          closes_on?: string | null;
          nominations_announced_on?: string | null;
          ceremony_on?: string | null;
          status?: Database["public"]["Enums"]["season_status"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ceremony_year?: number;
          eligibility_year?: number | null;
          eligibility_period?: string | null;
          opens_on?: string | null;
          closes_on?: string | null;
          nominations_announced_on?: string | null;
          ceremony_on?: string | null;
          status?: Database["public"]["Enums"]["season_status"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sources: {
        Row: {
          id: string;
          name: string;
          source_types: string[];
          homepage_url: string;
          editorial_status: Database["public"]["Enums"]["source_editorial_status"];
          technical_status: Database["public"]["Enums"]["source_technical_status"];
          publication_status: Database["public"]["Enums"]["source_publication_status"];
          last_reviewed_on: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          source_types: string[];
          homepage_url: string;
          editorial_status: Database["public"]["Enums"]["source_editorial_status"];
          technical_status: Database["public"]["Enums"]["source_technical_status"];
          publication_status: Database["public"]["Enums"]["source_publication_status"];
          last_reviewed_on?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          source_types?: string[];
          homepage_url?: string;
          editorial_status?: Database["public"]["Enums"]["source_editorial_status"];
          technical_status?: Database["public"]["Enums"]["source_technical_status"];
          publication_status?: Database["public"]["Enums"]["source_publication_status"];
          last_reviewed_on?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      set_updated_at: {
        Args: Record<PropertyKey, never>;
        Returns: unknown;
      };
    };
    Enums: {
      category_subject: "film" | "person";
      film_release_status: "announced" | "upcoming" | "released";
      season_status:
        "preparation" | "active" | "nominations_announced" | "closed";
      source_editorial_status:
        "candidate" | "sampled" | "selected" | "paused" | "rejected";
      source_publication_status:
        | "not-reviewed"
        | "review-before-publish"
        | "publishable"
        | "replace-before-publish";
      source_technical_status:
        "manual" | "prototype" | "automated" | "failing" | "retired";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};
